//! `cargo xtask formula`: render the Homebrew formula (`Formula/acs.rb` in
//! the tap `scripts/update-tap.sh` pushes to, docs/VERSIONING.md
//! "Homebrew") for a release from its `SHA256SUMS`.
//!
//! The formula installs the release archive for the machine — the complete
//! build (DESIGN §8.1), so a brewed acs installs every Linux remote; a build
//! from source would be slim. `scripts/update-tap.sh` commits it to the tap.
//!
//! Its URLs, like the packaged installer's, are this build's rather than
//! acs's: a fork that builds with `ACS_DEFAULT_RELEASES_URL` gets a formula
//! pointing at its own releases with no edit here (acs-x57).

use crate::upstream;

/// The archive target per Homebrew `on_<os>` and `on_<cpu>` block.
const TARGETS: &[(&str, &[(&str, &str)])] = &[
    (
        "macos",
        &[
            ("arm", "aarch64-apple-darwin"),
            ("intel", "x86_64-apple-darwin"),
        ],
    ),
    (
        "linux",
        &[
            ("arm", "aarch64-unknown-linux-musl"),
            ("intel", "x86_64-unknown-linux-musl"),
        ],
    ),
];

/// The SHA-256 of `file` in a `SHA256SUMS` text (`<hex>  <file>` lines).
pub fn checksum<'a>(sums: &'a str, file: &str) -> Option<&'a str> {
    sums.lines().find_map(|l| {
        let (hash, name) = l.split_once(char::is_whitespace)?;
        let name = name.trim_start().trim_start_matches('*');
        let hex = hash.len() == 64 && hash.bytes().all(|b| b.is_ascii_hexdigit());
        (name == file && hex).then_some(hash)
    })
}

/// `Formula/acs.rb` for `version`, every archive's checksum from `sums`,
/// pointing at wherever this build publishes.
pub fn render(version: &str, sums: &str) -> Result<String, String> {
    render_with(version, sums, upstream::releases())
}

/// [`render`] against a given releases URL, so a fork's formula can be
/// tested without rebuilding acs.
pub fn render_with(version: &str, sums: &str, releases: &str) -> Result<String, String> {
    // A release: X.Y.Z, no `v`, no pre-release.
    let release = matches!(acs::release::parse_version(version), Some((_, None)));
    if version.starts_with('v') || !release {
        return Err(format!("version wants X.Y.Z, not '{version}'"));
    }
    let repo = upstream::repo(releases);
    let mut f = String::new();
    f.push_str(&format!(
        "# Generated by `cargo xtask formula` in {repo} for each release\n"
    ));
    f.push_str("# (scripts/update-tap.sh): edit the generator there, not this file.\n");
    // The release key, in a repository of its own (acs-o9v): acs and its
    // installer both carry this key to check a release's SHA256SUMS.sig
    // with, and a copy that travels with the download is only worth as
    // much as the download. This is the second source to check it against.
    f.push_str("#\n# acs releases are signed; SHA256SUMS.sig is checked against this key:\n");
    f.push_str(&format!("#   {}\n", acs::signature::RELEASE_KEY));
    f.push_str("# Verify a release by hand:\n");
    f.push_str(&format!(
        "#   printf '{} namespaces=\"{}\" %s\\n' \"$key\" > allowed\n",
        acs::signature::IDENTITY,
        acs::signature::NAMESPACE
    ));
    f.push_str(&format!(
        "#   ssh-keygen -Y verify -f allowed -I {} -n {} -s SHA256SUMS.sig < SHA256SUMS\n",
        acs::signature::IDENTITY,
        acs::signature::NAMESPACE
    ));
    f.push_str("class Acs < Formula\n");
    f.push_str("  desc \"Persistent, reconnecting remote shells over ssh\"\n");
    f.push_str(&format!("  homepage \"{repo}\"\n"));
    f.push_str("  license \"MIT\"\n\n");
    f.push_str("  livecheck do\n    url :stable\n    strategy :github_latest\n  end\n");
    for (os, cpus) in TARGETS {
        f.push_str(&format!("\n  on_{os} do\n"));
        for (i, (cpu, target)) in cpus.iter().enumerate() {
            let file = format!("acs-{version}-{target}.tar.gz");
            let sha = checksum(sums, &file).ok_or(format!("SHA256SUMS has no {file}"))?;
            if i > 0 {
                f.push('\n');
            }
            f.push_str(&format!("    on_{cpu} do\n"));
            f.push_str(&format!(
                "      url \"{releases}/download/v{version}/{file}\"\n"
            ));
            f.push_str(&format!("      sha256 \"{sha}\"\n"));
            f.push_str("    end\n");
        }
        f.push_str("  end\n");
    }
    // The archive holds acs-<version>-<target>/{acs,README.md}; brew unpacks
    // into that directory. `acs upgrade` defers to brew for a Cellar path.
    f.push_str("\n  def install\n    bin.install \"acs\"\n  end\n\n");
    // `version` is the one brew reads from the URL. The complete build lists
    // both Linux targets among the remotes it can install (in its own order):
    // a brewed binary must still carry its payloads.
    f.push_str("  test do\n");
    f.push_str("    out = shell_output(\"#{bin}/acs --version\")\n");
    f.push_str("    assert_match \"acs #{version} \", out\n");
    f.push_str("    remotes = out[/^installs remotes: (.*)$/, 1].to_s.split(\", \")\n");
    f.push_str("    assert_includes remotes, \"x86_64-unknown-linux-musl\"\n");
    f.push_str("    assert_includes remotes, \"aarch64-unknown-linux-musl\"\n");
    f.push_str("  end\nend\n");
    Ok(f)
}

pub fn main(args: &[String]) -> Result<(), String> {
    let mut version = None;
    let mut sums = None;
    let mut out = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        let mut val = || it.next().cloned().ok_or(format!("{a} needs a value"));
        match a.as_str() {
            "--version" => version = Some(val()?.trim_start_matches('v').to_string()),
            "--sums" => sums = Some(val()?),
            "--out" => out = Some(val()?),
            other => return Err(format!("unknown argument {other}")),
        }
    }
    let (Some(version), Some(sums)) = (version, sums) else {
        return Err(
            "usage: cargo xtask formula --version X.Y.Z --sums SHA256SUMS [--out FILE]".into(),
        );
    };
    let text = std::fs::read_to_string(&sums).map_err(|e| format!("{sums}: {e}"))?;
    let formula = render(&version, &text)?;
    match out {
        Some(p) => std::fs::write(&p, formula).map_err(|e| format!("{p}: {e}")),
        None => {
            print!("{formula}");
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sums(version: &str) -> String {
        [
            "aarch64-apple-darwin",
            "aarch64-unknown-linux-musl",
            "x86_64-apple-darwin",
            "x86_64-unknown-linux-musl",
        ]
        .iter()
        .enumerate()
        .map(|(i, t)| format!("{}  acs-{version}-{t}.tar.gz\n", i.to_string().repeat(64)))
        .collect()
    }

    #[test]
    fn checksums_are_found_by_file_name() {
        let s = sums("1.2.3");
        assert_eq!(
            checksum(&s, "acs-1.2.3-x86_64-apple-darwin.tar.gz"),
            Some("2".repeat(64).as_str())
        );
        assert_eq!(checksum(&s, "acs-1.2.3-x86_64-apple-darwin"), None);
        // Binary-mode marker, and a malformed hash is no hash.
        let star = format!("{}  *a.tar.gz\nnothex  b.tar.gz\n", "f".repeat(64));
        assert_eq!(checksum(&star, "a.tar.gz"), Some("f".repeat(64).as_str()));
        assert_eq!(checksum(&star, "b.tar.gz"), None);
    }

    /// acs-o9v: the tap is the second source for the release key, so the
    /// formula carries it — a key that only ever travels with the download
    /// is worth no more than the download. README and DESIGN §7.5 both say
    /// it is here.
    #[test]
    fn the_formula_carries_the_release_key_to_check_it_against() {
        let f = render("1.2.3", &sums("1.2.3")).unwrap();
        assert!(
            f.contains(acs::signature::RELEASE_KEY),
            "the formula does not carry the release key:\n{f}"
        );
        assert!(f.contains("SHA256SUMS.sig"), "{f}");
        assert!(
            f.contains(&format!("-n {}", acs::signature::NAMESPACE)),
            "{f}"
        );
        // It is all comment: the formula must still be the same Ruby.
        for line in f.lines().take_while(|l| !l.starts_with("class ")) {
            assert!(line.starts_with('#'), "not a comment: {line:?}");
        }
    }

    /// acs-x57: the formula's homepage and download URLs are this build's
    /// releases, so a fork needs no edit here. Rendered against a fork's
    /// URL, nothing upstream is left in it.
    #[test]
    fn the_formula_points_at_the_builds_own_releases() {
        // This build's, whichever it is.
        let f = render("1.2.3", &sums("1.2.3")).unwrap();
        let releases = acs::release::DEFAULT_RELEASES_URL;
        assert!(
            f.contains(&format!(
                "  homepage \"{}\"\n",
                crate::upstream::repo(releases)
            )),
            "{f}"
        );
        assert!(
            f.contains(&format!("url \"{releases}/download/v1.2.3/")),
            "{f}"
        );
        // A fork's, with no rebuild: nothing of acs's own survives.
        let fork = "https://github.com/someone/acs-fork/releases";
        let f = render_with("1.2.3", &sums("1.2.3"), fork).unwrap();
        assert!(
            f.contains("  homepage \"https://github.com/someone/acs-fork\"\n"),
            "{f}"
        );
        assert!(
            f.contains(
                "url \"https://github.com/someone/acs-fork/releases/download/v1.2.3/acs-1.2.3-aarch64-apple-darwin.tar.gz\""
            ),
            "{f}"
        );
        assert!(!f.contains("michel-onstein"), "{f}");
    }

    #[test]
    fn each_os_and_cpu_gets_its_archive_and_checksum() {
        let f = render("1.2.3", &sums("1.2.3")).unwrap();
        assert!(f.contains("class Acs < Formula\n"));
        // brew reads the version from the URLs (`brew audit --strict`
        // rejects a redundant `version`).
        assert!(!f.contains("  version "));
        // The first CPU of an OS block, whole.
        let block = |os: &str, cpu: &str, target: &str, digit: char| {
            format!(
                "on_{os} do\n    on_{cpu} do\n      url \"https://github.com/michel-onstein/acs/releases/download/v1.2.3/acs-1.2.3-{target}.tar.gz\"\n      sha256 \"{}\"\n    end\n",
                digit.to_string().repeat(64)
            )
        };
        assert!(
            f.contains(&block("macos", "arm", "aarch64-apple-darwin", '0')),
            "{f}"
        );
        let intel = "    on_intel do\n      url \"https://github.com/michel-onstein/acs/releases/download/v1.2.3/acs-1.2.3-x86_64-apple-darwin.tar.gz\"\n      sha256 \"2222";
        assert!(f.contains(intel), "{f}");
        // Linux: the static musl builds, with their own checksums.
        assert!(
            f.contains(&block("linux", "arm", "aarch64-unknown-linux-musl", '1')),
            "{f}"
        );
        assert!(f.contains("acs-1.2.3-x86_64-unknown-linux-musl.tar.gz\"\n      sha256 \"3333"));
        assert!(f.find("on_macos do").unwrap() < f.find("on_linux do").unwrap());
        // Installs the binary; the test checks the version and the payloads.
        assert!(f.contains("bin.install \"acs\""));
        assert!(f.contains("assert_match \"acs #{version} \""));
        // Both Linux payloads, in whatever order the build lists them (a
        // Linux build puts its own target first).
        assert!(f.contains("assert_includes remotes, \"x86_64-unknown-linux-musl\"\n"));
        assert!(f.contains("assert_includes remotes, \"aarch64-unknown-linux-musl\"\n"));
        assert!(f.ends_with("  end\nend\n"));
    }

    #[test]
    fn a_missing_archive_or_bad_version_is_an_error() {
        let partial: String = sums("1.2.3")
            .lines()
            .filter(|l| !l.contains("aarch64-unknown-linux-musl"))
            .map(|l| format!("{l}\n"))
            .collect();
        assert_eq!(
            render("1.2.3", &partial).unwrap_err(),
            "SHA256SUMS has no acs-1.2.3-aarch64-unknown-linux-musl.tar.gz"
        );
        // Another release's sums do not fit.
        assert!(render("1.2.4", &sums("1.2.3")).is_err());
        assert!(render("latest", &sums("1.2.3")).is_err());
        assert!(render("1.2.3-rc1", &sums("1.2.3-rc1")).is_err());
        assert!(render("", "").is_err());
    }
}
